<html>
<?php include 'header.php';?>
<body class="fall artificial-intelligence">
<div class="fall overlay"></div>
<div id="main">
<?php include 'navbar.php';?>
<div id="content">
<div id="title"><p>Artificial Intelligence</p>Lee Spector</div>
<div id="course-description"><p>Course Description</p>Artificial Intelligence is a branch of computer science concerned with the development of computer systems that "think." In this course we will explore the core ideas of artificial intelligence through readings, presentations, discussions, and hands-on programming activities. A range of practical artificial intelligence techniques will be covered, and students will complete programming projects to demonstrate engagement with the themes of the course. Prerequisite: One programming course (in any language).</div>
<div id="course-objectives"><p>Course Objectives</p>The objectives of this course were for students to: gain familiarity with a range of concepts and computational techniques that have been developed by AI researchers over history of the field; apply several of these concepts and techniques to hands-on research and development activities involving "intelligent agents" in virtual worlds; develop skills in "functional"-style programming; conduct independent programming-based project work; develop project presentation skills; and work collaboratively with classmates. Students were evaluated on the basis of attendance, participation, a portfolio of code and text submitted in increments with scheduled deadlines, and in-class "demo" presentations on assignment due dates. Students were expected to demonstrate through their participation, code, and text that they had read and thought about the course readings.</div>
<div id="prof-eval"><p>Professor's Evaluation</p>Andy's performance in this course was generally good. He attended regularly, and although he seemed to lose focus and to be less productive for a period in the middle of the course (failing to turn in one reaction paper), overall he engaged significantly with the course material and contributed to the work of the class in constructive ways. Andy's programming portfolio demonstrates growing skills, mostly applied to the development of controllers for agents in virtual worlds and to the generation of English sentences. For his text portfolio Andy wrote thoughtfully about a range of topics including the plusses an minuses of various control architectures, strategies for natural language processing, and the possibility of machine consciousness. Andy's in-class presentations were generally strong. In sum, Andy did well in this course and is prepared to conduct more advanced work on artificial intelligence.</div>
<div id="self-eval"><p>Self Evaluation</p>Andy's performance in this course was generally good. He attended regularly, and although he seemed to lose focus and to be less productive for a period in the middle of the course (failing to turn in one reaction paper), overall he engaged significantly with the course material and contributed to the work of the class in constructive ways. Andy's programming portfolio demonstrates growing skills, mostly applied to the development of controllers for agents in virtual worlds and to the generation of English sentences. For his text portfolio Andy wrote thoughtfully about a range of topics including the plusses an minuses of various control architectures, strategies for natural language processing, and the possibility of machine consciousness. Andy's in-class presentations were generally strong. In sum, Andy did well in this course and is prepared to conduct more advanced work on artificial intelligence.</div>
</div>
</div>
</body>
<?php include 'scripts.php';?>
</html>
